sudo: required
dist: trusty
language: python

before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg libavcodec-dev libavformat-dev libswscale-dev libgtk2.0-dev
  - sudo apt-get install -y python-tk python3-tk

install:
  - pip install -r requirements.txt
  - pip install codecov

cache:
  pip: true
  directories:
    - $OPENCV_INSTALL_PATH

env:
  global:
    - COLUMNS=80

python:
  - "3.6"

script: coverage run --source=ganbase setup.py test

after_success: codecov

deploy:
  provider: pypi
  user: innerlee
  password:
    secure: empty
  on:
    branch: master
    tags: true
    python: "3.6"
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_upload_docs: true
