sudo: required
dist: trusty
language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install python-sphinx
  - which python
  - python --version
  - which pip

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install recommonmark
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install http://download.pytorch.org/whl/cpu/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl
  - pip install torchvision
  - python setup.py install
  - pip install --upgrade pytest

cache:
  pip: true

env:
  global:
  - COLUMNS=80
  - secure: IfDMQfW5lWTU07dRiQ7UL8OtVI18zBECgKkFLnX3j3F63nIWpt1e1KWd3JxUKHJkdFett3gW5oa/z2wRy9BhKKKXHhPRA7XqoClV5e5CZpz3q023hDsfWRvhHTPdFn65ghzspv2dhbzYK7mISS2vH1IZV6zA1BIuG2gOEzXKk+/CYoftVmEz2O98o/yOPkHiVQnEPey233KHVb7PU1xRJLSI4M+HTSXGSjpalMzaOFNghB78iKtgZ4JcmugKFZGfaAEa5pvTgbPzrXAqU04ISlTwDSu1Pq465xRKqqLTsri6F/waaCabmJU6MBRo8d8D0cVo5gIvx51HUcBShvamNXrNtVjQzFGnnwFouRSiMMAZwGXCJa+FJUaR27K2mD8FOgdtDyVWA4KzDStjXqkF65JanQAAifbRI/1/KDi2YmACqJUg+fFfQwxQqikt5Tw9yEywf/wj29LMRNmc1GOSp2aSqCPz5Ge5xq+UgjGdXH+P62pj3RBMr4sYJZVFrjrI8tT8G9qUGlYCJn5qcLEvdFNYMSsmKcnO2yjNZhI/o4uwbk0VC4IJ2i1RNVBccc+5YHwt0uYJAoQ48DDWYua5jdW+hs2etPc8x5JMKLw9VyQt3xFvOBRRKig0cylKdt0q6CJGdbhmnV1Ym6MlfDWe+xOffWohG04Tvi8VxGw24EQ=

python:
  - '3.6'

script:
  - coverage run --source=ganbase setup.py test
  - coverage report
  - set -e
  - pwd
  - cd docs
  - make html
  - cd ..
  - pip install doctr
  - doctr deploy .
  - pytest

after_success:
  - codecov

deploy:
  provider: pypi
  user: innerlee
  password:
    secure: etTtrXcKU2RMoAk+ueB3V//5w8uLVxr8ZJWwn74V2J2THQdsVVs3QCwo2qLjZuYUPYNWRqZUHIy4at2ZZYLNQl4ZwvY9eA9+aGA+SswNnK1eCTzdoMkKKHvFRj2+gGewdfp8f0NnW0bReli/SJwfqwybbrHRMa3zBu0hYhCgoCeeIdx6kADV89nS9Kxm1q6wgiogahAAe1wK/ujihHiPEmO0U1/zTSR45y6PqErZJH6fDDoJ406ZlDxt8A+HoYanXdxgOkMiT4VfZ82vfX57lHmJ0pK1UA5T2fwUXtUCefT/vdleOiHWrQP9T7WGBQ+1nUwSMnYmyxS5bz7EDwY1Bh8V+JpHXQxkacZpimUmnw5LApNkQ/PE1LLoK6qptxraFtcx40p7y2HLQfGEMYIa8jM/0TDu+M2EsoWjF7zDEAkrs7rbbAr8YIrNwMKJVjH0wW1CQGuHhh4D5v6ACLntQ70himDokqanmYN/TJMBtgfO2ry/TuD+JVDQHg15YLgk3yTYGj4DxcpPKRyu2V37vBtsPEDnxb4MsLwMw4YiM+kK69GqrfRB1bqprMt3t0aXBrTBsZYG1AGf2Fyx/Ir6S8o9rijKGv7ZkN4QKWN7x5uKC/f0ymgkLPMGN45f2xuIAdER7sQrXqKSkLFLQM6pxBbrug86ktpRQbAX5setJ0Y=
  on:
    branch: master
    tags: true
    python: '3.6'
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_upload_docs: true
